experiment:
  name: "pure_low_single_night_100k_pixel_trans_minus"
  auto_name: true

data:
  path: "datasets/BDD_below40"
  mode: "pure_low_single"
  crop_size: 512
  batch_size: 4
  num_workers: 4

model:
  name: "RetinexPixelTransMinus"
  dim: 24
  l_heads: 1
  l_ffn_expansion: 2.66
  use_dp: false
  gpu_id: "0"

training:
  max_iterations: 10000
  lr: 0.0001
  warmup_iterations: 1000
  log_interval: 1000
  save_ckpt_interval: 0
  eval:
    eval_interval: 500
    save_img_interval: 5000
    save_best_ckpt: true

loss:
  mode: "pure_low_single_pixel"
  recon_weight: 1
  anchor_weight: 0.05
  bdsp_weight: 0.05
  smooth_weight: 0.1

resume:
  checkpoint: ""
  weights: ""

device: "cuda"
